debian: check for required packages on host

diff --git a/Makefile.debian b/Makefile.debian
--- a/Makefile.debian
+++ b/Makefile.debian
@@ -8,6 +8,8 @@ RUN_AS_USER=user
 DEBIANVERSION=$(DIST)
 export DEBIANVERSION
 
+DEBIAN_DEPENDENCIES := dpkg-dev debootstrap
+
 ifneq (,$(DEBIAN_BUILD_DIRS))
 packagefile = $(shell head -n 1 $(ORIG_SRC)/debian/changelog  | awk '{print $$1, $$2}' | sed 's/\([a-zA-Z\-]*\) (\(.*\))/\1_\2/')
 endif
@@ -47,7 +49,14 @@ $(CHROOT_DIR)/home/user/.prepared_base: ./prepare-chroot-debian
 	@touch $(CHROOT_DIR)/home/user/.prepared_base
 
 dist-prep:
-	@true
+	@if ! which rpm >/dev/null 2>&1; then \
+		echo "WARNING: rpm executable not found (are you on cygwin?)"; \
+	elif [ $(VERBOSE) -gt 0 ]; then \
+		echo "currently installed dependencies:"; \
+		rpm -q $(DEBIAN_DEPENDENCIES) || exit 1; \
+	else \
+		rpm -q $(DEBIAN_DEPENDENCIES) >/dev/null 2>&1 || exit 1; \
+	fi
 
 dist-build-dep:
 	./update-local-repo.sh $(DIST)
