verify-git-tag: fix indentation

diff --git a/scripts/verify-git-tag b/scripts/verify-git-tag
--- a/scripts/verify-git-tag
+++ b/scripts/verify-git-tag
@@ -15,7 +15,7 @@ source "$BUILDER_DIR/scripts/common"
 set -o pipefail
 
 if [ "$NO_CHECK" == "1" ]; then
-	exit 0
+    exit 0
 fi
 
 if [ -n "$KEYRING_DIR_GIT" ]; then
@@ -31,16 +31,16 @@ if [ -n "$KEYRING_DIR_GIT" ]; then
         gpg --import qubes-developers-keys.asc
         touch "$GNUPGHOME/pubring.gpg"
     fi
-	maintainers=$(env | grep -oP '^ALLOWED_COMPONENTS_[a-fA-F0-9]{40}')
+    maintainers=$(env | grep -oP '^ALLOWED_COMPONENTS_[a-fA-F0-9]{40}')
     for maintainer in $maintainers
     do
         allowed_components=("${!maintainer}")
-		COMPONENT="$(basename "$1")"
-		COMPONENT="${COMPONENT//./builder}"
+        COMPONENT="$(basename "$1")"
+        COMPONENT="${COMPONENT//./builder}"
         if elementIn "$COMPONENT" ${allowed_components[@]}; then
             keyid=${maintainer//ALLOWED_COMPONENTS_/}
-			gpg --import "$BUILDER_DIR/keys/$keyid.asc" || exit 1
-			echo "$keyid:6:" | gpg --import-ownertrust
+            gpg --import "$BUILDER_DIR/keys/$keyid.asc" || exit 1
+            echo "$keyid:6:" | gpg --import-ownertrust
         fi
     done
 fi
@@ -48,36 +48,36 @@ fi
 pushd "$1" > /dev/null || exit 2
 
 if [ -n "$2" ]; then
-	REF="$2"
+    REF="$2"
 else
-	REF="HEAD"
+    REF="HEAD"
 fi
 
 verify_tag() {
-	git verify-tag --raw "$1" 2>&1 | grep -q '^\[GNUPG:\] TRUST_\(FULLY\|ULTIMATE\)'
+    git verify-tag --raw "$1" 2>&1 | grep -q '^\[GNUPG:\] TRUST_\(FULLY\|ULTIMATE\)'
 }
 
 VALID_TAG_FOUND=0
 for tag in $(git tag --points-at="$REF"); do
-	if verify_tag "$tag"; then
-		VALID_TAG_FOUND=1
-	else
-		if [ "0$VERBOSE" -ge 1 ]; then
-			echo "---> One of signed tag cannot be verified:"
-			git tag -v "$tag"
-		fi
-	fi
+    if verify_tag "$tag"; then
+        VALID_TAG_FOUND=1
+    else
+        if [ "0$VERBOSE" -ge 1 ]; then
+            echo "---> One of signed tag cannot be verified:"
+            git tag -v "$tag"
+        fi
+    fi
 done
 
 if [ "$VALID_TAG_FOUND" -eq 0 ]; then
-	echo "No valid signed tag found!"
-	if [ "0$VERBOSE" -eq 0 ]; then
-		if [ -n "$(git describe "$REF")" ]; then
-			echo "---> One of invalid tag:"
-			git tag -v $(git describe "$REF")
-		fi
-	fi
-	exit 1
+    echo "No valid signed tag found!"
+    if [ "0$VERBOSE" -eq 0 ]; then
+        if [ -n "$(git describe "$REF")" ]; then
+            echo "---> One of invalid tag:"
+            git tag -v $(git describe "$REF")
+        fi
+    fi
+    exit 1
 fi
 
 exit 0
